# kitchen.py
# Kitchen / Dining Hall 
# A large, industrial space where meals are prepared and distributed to inmates. 
# Players may find opportunities here related to food contamination, smuggling items, or befriending kitchen staff. 
# Time spent: Rare

# Kitchen/Dining Hall Inventory & Function Index:

# Food Preparation Areas: Separate stations for preparing different types of food (e.g., vegetables, proteins, grains) equipped with industrial-strength appliances like stovetops, ovens, mixers, and slicers.

# Ingredient Storage: Large walk-in freezers and coolers filled with prepackaged ingredients used in meal preparation. Some shelves may contain less desirable items suitable for tampering or contamination.

# Serving Line: A counter where cooked food is portioned and served onto trays before being transported to the dining hall. This area offers opportunities for players to introduce unauthorized substances into the food supply.

# Dishwashing Station: An extensive area featuring industrial dishwashers, sinks, and scrubbing brushes where dirty utensils and dishes are cleaned after each meal. This environment provides chances for players to hide items or retrieve previously planted objects.

# Garbage Disposal: A system for collecting and disposing of food waste generated by the kitchen operations. It includes compactors, dumpsters, and conveyor belts designed to handle large volumes of refuse efficiently.

# Dining Hall: A vast room capable of accommodating all inmates at once for mealtimes. Tables and benches are arranged in rows, separated by narrow aisles for serving purposes. Supervisory staff monitor the dining hall from elevated platforms located at strategic points.

# Vending Machines: Similar to those found elsewhere in the prison, vending machines in the dining hall offer snacks, drinks, and basic essentials like toiletries for purchase using a prepaid system accessible only to inmates.

# Sanitation Stations: Located near the entrance of the dining hall, these stations provide hand sanitizer and disposable paper towels for inmate use before and after eating. They also double as makeshift hiding spots for small items.

# Emergency Button: Like other locations in PRISON-RIOT, the kitchen/dining hall has an emergency button that triggers an alarm signal when pressed. Abuse of this feature may result in disciplinary action.

# In the heavily guarded and controlled setting of the kitchen/dining hall, players must navigate complex dynamics involving power struggles, resource management, and the pursuit of survival. 
# Opportunities for manipulation abound through food contamination or smuggling operations, while befriending kitchen staff could lead to valuable alliances or insider information about the inner workings of Raiyaku Penitentiary. 
# However, any actions taken in this sensitive environment must be carefully planned and executed to avoid attracting unwanted attention or retaliation from authorities.
