# yard.py
# Prison Yard
# An open space where inmates can exercise, socialize, or participate in organized events like sports matches. 
# It serves as a setting for both casual encounters and strategic opportunities. 
# Time spent: Medium-High

# Prison Yard Inventory & Function Index:

# Field/Court Area: The main portion of the yard dedicated to various recreational activities. Depending on the facilities available, this area might include a basketball court, soccer field, volleyball net, or other sporting amenities.

# Benches/Seating: Metal benches positioned around the perimeter of the field/court. They provide seating for spectators who wish to watch games or events taking place in the prison yard.

# Weightlifting Station: A section of the yard containing weightlifting equipment like dumbbells, barbells, and pull-up bars. This area enables inmates to engage in strength training exercises to maintain muscle mass and overall physical health.

# Running Track: A marked path surrounding the field/court area used for jogging, running laps, or other cardiovascular workouts. The track has distance markers to help inmates keep track of their progress.

# Showers/Bathrooms: Separate facilities for male and female inmates to bathe and attend to personal hygiene needs after engaging in physical activities. These areas are typically monitored by security cameras and have limited privacy options due to the communal nature of the prison environment.

# Recreational Equipment Storage: A locked storage container containing balls, nets, goals, and other equipment necessary for organized sports and recreational activities in the prison yard. Access is restricted to authorized personnel.

# Guard Towers: Elevated structures situated at strategic points throughout the prison yard. Guards stationed in these towers monitor the activity below through surveillance cameras and two-way communication systems. Their presence serves as a deterrent against violent altercations or escape attempts.

# Announcement System: A loudspeaker system capable of broadcasting messages and instructions to all inmates in the prison yard. This tool allows guards to communicate rules, schedule events, or make announcements about changes in daily routines.

# Snack Bar/Vending Machines: A small kiosk offering snacks, drinks, and basic essentials like toiletries. Operated by prison staff or selected inmates, this facility provides an opportunity for social interaction while satisfying basic needs.

# Trash Cans/Dumpsters: Large containers located around the prison yard for disposing of waste generated by inmates during their activities. Regular cleaning and maintenance ensure sanitary conditions within the yard.

# The prison yard offers numerous opportunities for both recreation and manipulation within PRISON-RIOT. 
# As an open space with minimal direct supervision, it becomes a crucial location for alliance building, information exchange, and clandestine operations among inmates. 
# However, the constant presence of guards, surveillance systems, and strict rules serve as reminders that even here, there is no true freedom from the oppressive regime governing Raiyaku Penitentiary.
