# infirmary.py
# Infirmary 
# A medical facility where injured or sick inmates seek treatment, often leading to interactions with healthcare staff or potential allies among the patients. 
# Time spent: Occasional

# Infirmary Inventory & Function Index:

# Examination Rooms: Private rooms equipped with examination tables, medical instruments, and storage cabinets containing medications and supplies. Healthcare professionals conduct diagnoses and administer treatments in these areas.

# Triage Area: A designated space where newly arrived patients are assessed by nurses or physicians to determine the severity of their injuries or illnesses. This area helps prioritize care and direct patients to appropriate treatment facilities.

# Treatment Room: A larger, open area containing beds and medical equipment necessary for providing care to multiple patients simultaneously. Nurses and doctors tend to patients in this area under the supervision of a lead medical professional.

# Pharmacy: A separate compartment within the infirmary containing medications organized by type and indication. Licensed healthcare personnel dispense prescriptions to authorized patients following established protocols.

# Isolation Ward: A section of the infirmary reserved for treating highly contagious patients or those suffering from severe illnesses requiring quarantine. This area features negative pressure ventilation systems designed to minimize the spread of airborne pathogens.

# Medical Supply Storage: Locked cabinets and rooms containing additional medical equipment, supplies, and personal protective gear for healthcare staff. Access is restricted to authorized personnel.

# Staff Lounge/Breakroom: A small area furnished with a refrigerator, microwave, coffee maker, and comfortable seating for healthcare staff to relax during breaks or meal periods.

# Secure Waste Disposal: A system for safely disposing of biohazardous waste generated by patient care activities. This includes specialized containers, incinerators, and autoclaves to sterilize items before discarding them.

# Camera Coverage: The infirmary is equipped with surveillance cameras similar to those found in other high-security areas of Raiyaku Penitentiary. These recordings serve as documentation of patient encounters and help deter malpractice or misconduct by both inmates and staff members.

# Alarm System: Similar to the emergency buttons found elsewhere in the prison, infirmaries typically have alarm systems that can be activated in case of emergencies or security breaches.

# The infirmary serves as a nexus for various forms of interaction between inmates, healthcare staff, and potential allies among the patient population. 
# While its primary function is to provide medical care, it also presents opportunities for manipulation, information exchange, and strategic partnerships. 
# Players should approach this location with caution and discretion, balancing the need for assistance with the risks associated with trusting others within the confines of PRISON-RIOT.
